// frontend/src/lib/components/JobStatus.svelte
<script lang="ts">
  import { getJobStatus, type JobResponse, type JobStatus } from "../api";

  let {
    jobId,
    onComplete,
  }: {
    jobId: string;
    onComplete: (job: JobResponse) => void;
  } = $props();

  let status = $state<JobStatus>("PENDING");
  let progress = $state("Starting...");

  const STATUS_LABELS: Record<JobStatus, string> = {
    PENDING: "En attente...",
    DOWNLOADING_AUDIO: "Telechargement de l'audio...",
    DOWNLOADING_CHAT: "Telechargement du chat...",
    ANALYZING_AUDIO: "Analyse audio en cours...",
    ANALYZING_CHAT: "Analyse du chat...",
    SCORING: "Calcul des scores...",
    TRIAGE: "Pre-analyse LLM...",
    CLIPPING: "Extraction des clips...",
    VERTICAL: "Generation des clips verticaux...",
    TRANSCRIBING: "Transcription des clips...",
    LLM_ANALYSIS: "Analyse LLM en cours...",
    DONE: "Terminé !",
    ERROR: "Erreur",
  };

  const STATUS_ORDER: JobStatus[] = [
    "PENDING",
    "DOWNLOADING_AUDIO",
    "DOWNLOADING_CHAT",
    "ANALYZING_AUDIO",
    "ANALYZING_CHAT",
    "SCORING",
    "TRIAGE",
    "CLIPPING",
    "VERTICAL",
    "TRANSCRIBING",
    "LLM_ANALYSIS",
    "DONE",
  ];

  let progressPct = $derived(() => {
    const idx = STATUS_ORDER.indexOf(status);
    if (idx < 0) return 0;
    return Math.round((idx / (STATUS_ORDER.length - 1)) * 100);
  });

  $effect(() => {
    const interval = setInterval(async () => {
      try {
        const job = await getJobStatus(jobId);
        status = job.status;
        progress = job.progress || STATUS_LABELS[job.status];

        if (job.status === "DONE" || job.status === "ERROR") {
          clearInterval(interval);
          onComplete(job);
        }
      } catch {
        // Network error — keep polling
      }
    }, 2000);

    return () => clearInterval(interval);
  });
</script>

<div class="w-full max-w-2xl mx-auto text-center">
  <div class="mb-6">
    <div class="inline-block animate-spin text-purple-400 text-3xl mb-4">&#9696;</div>
    <p class="text-lg text-zinc-300">{progress}</p>
    <p class="text-sm text-zinc-500 mt-1">{STATUS_LABELS[status]}</p>
  </div>

  <!-- Progress bar -->
  <div class="w-full bg-zinc-800 rounded-full h-2 overflow-hidden">
    <div
      class="bg-purple-500 h-full rounded-full transition-all duration-500"
      style="width: {progressPct()}%"
    ></div>
  </div>

  <!-- Step indicators -->
  <div class="flex justify-between mt-3 text-xs text-zinc-600">
    {#each STATUS_ORDER.slice(1, -1) as step}
      <span
        class={STATUS_ORDER.indexOf(status) >= STATUS_ORDER.indexOf(step)
          ? "text-purple-400"
          : ""}
      >
        {STATUS_LABELS[step].replace("...", "")}
      </span>
    {/each}
  </div>
</div>

// frontend/src/components/JobStatus.tsx
import { useState, useEffect, useCallback } from "react";
import { getJobStatus, type JobResponse, type JobStatusType } from "../lib/api";

interface Props {
  jobId: string;
  onComplete: (job: JobResponse) => void;
}

const STATUS_LABELS: Record<JobStatusType, string> = {
  PENDING: "En attente...",
  DOWNLOADING_AUDIO: "Telechargement audio",
  DOWNLOADING_CHAT: "Telechargement chat",
  ANALYZING_AUDIO: "Analyse audio",
  ANALYZING_CHAT: "Analyse du chat",
  SCORING: "Calcul des scores",
  TRIAGE: "Pre-analyse LLM",
  CLIPPING: "Extraction des clips",
  VERTICAL: "Clips verticaux",
  TRANSCRIBING: "Transcription",
  LLM_ANALYSIS: "Analyse IA",
  DONE: "Termine !",
  ERROR: "Erreur",
};

const STATUS_ORDER: JobStatusType[] = [
  "PENDING",
  "DOWNLOADING_AUDIO",
  "DOWNLOADING_CHAT",
  "ANALYZING_AUDIO",
  "ANALYZING_CHAT",
  "SCORING",
  "TRIAGE",
  "CLIPPING",
  "VERTICAL",
  "TRANSCRIBING",
  "LLM_ANALYSIS",
  "DONE",
];

function getProgress(status: JobStatusType): number {
  const idx = STATUS_ORDER.indexOf(status);
  if (idx < 0) return 0;
  return Math.round((idx / (STATUS_ORDER.length - 1)) * 100);
}

export default function JobStatus({ jobId, onComplete }: Props) {
  const [status, setStatus] = useState<JobStatusType>("PENDING");
  const [progress, setProgress] = useState("Demarrage...");

  const poll = useCallback(async () => {
    try {
      const job = await getJobStatus(jobId);
      setStatus(job.status);
      setProgress(job.progress || STATUS_LABELS[job.status]);
      if (job.status === "DONE" || job.status === "ERROR") {
        onComplete(job);
        return true;
      }
    } catch {
      // keep polling
    }
    return false;
  }, [jobId, onComplete]);

  useEffect(() => {
    let active = true;
    const interval = setInterval(async () => {
      if (!active) return;
      const done = await poll();
      if (done) clearInterval(interval);
    }, 2000);
    return () => {
      active = false;
      clearInterval(interval);
    };
  }, [poll]);

  const pct = getProgress(status);
  const currentIdx = STATUS_ORDER.indexOf(status);

  return (
    <div className="max-w-2xl mx-auto">
      <div className="glass rounded-2xl p-8 text-center">
        {/* Animated spinner */}
        <div className="relative w-16 h-16 mx-auto mb-6">
          <svg className="w-16 h-16 spinner" viewBox="0 0 50 50">
            <circle cx="25" cy="25" r="20" fill="none" stroke="rgba(168,85,247,0.15)" strokeWidth="3" />
            <circle cx="25" cy="25" r="20" fill="none" stroke="url(#grad)" strokeWidth="3" strokeDasharray="80" strokeLinecap="round" />
            <defs>
              <linearGradient id="grad">
                <stop offset="0%" stopColor="#a855f7" />
                <stop offset="100%" stopColor="#ec4899" />
              </linearGradient>
            </defs>
          </svg>
        </div>

        <p className="text-lg text-white font-medium mb-1">{progress}</p>
        <p className="text-sm text-zinc-500 mb-8">{STATUS_LABELS[status]}</p>

        {/* Progress bar */}
        <div className="w-full bg-white/[0.04] rounded-full h-1.5 overflow-hidden mb-6">
          <div
            className="progress-shimmer h-full rounded-full transition-all duration-700 ease-out"
            style={{ width: `${pct}%` }}
          />
        </div>

        {/* Step pills */}
        <div className="flex flex-wrap justify-center gap-2">
          {STATUS_ORDER.slice(1, -1).map((step, i) => {
            const isActive = currentIdx > i;
            const isCurrent = currentIdx === i + 1;
            return (
              <span
                key={step}
                className={`text-xs px-3 py-1 rounded-full transition-all ${
                  isCurrent
                    ? "bg-purple-500/20 text-purple-300 border border-purple-500/30"
                    : isActive
                      ? "text-zinc-400 bg-white/[0.03]"
                      : "text-zinc-700"
                }`}
              >
                {STATUS_LABELS[step]}
              </span>
            );
          })}
        </div>
      </div>
    </div>
  );
}
