// frontend/src/components/HotPoints.tsx
import { useState, useRef, useCallback } from "react";
import { clipUrl, type HotPoint } from "../lib/api";

interface Props {
  hotPoints: HotPoint[];
  vodTitle: string;
  vodGame: string;
  vodDuration: number;
  jobId: string;
  streamer: string;
  viewCount: number;
  streamDate: string;
}

interface SignalInfo {
  label: string;
  color: string;
  key: keyof HotPoint["signals"];
}

const SIGNALS: SignalInfo[] = [
  { label: "Volume", color: "#ef4444", key: "rms" },
  { label: "Chat", color: "#a855f7", key: "chat_speed" },
  { label: "Flux spectral", color: "#f97316", key: "spectral_flux" },
  { label: "Pitch", color: "#3b82f6", key: "pitch_variance" },
  { label: "Brillance", color: "#22c55e", key: "spectral_centroid" },
  { label: "ZCR", color: "#a1a1aa", key: "zcr" },
];

const CATEGORY_STYLES: Record<string, { label: string; color: string }> = {
  fun: { label: "Fun", color: "#eab308" },
  rage: { label: "Rage", color: "#ef4444" },
  clutch: { label: "Clutch", color: "#10b981" },
  skill: { label: "Skill", color: "#3b82f6" },
  fail: { label: "Fail", color: "#f97316" },
  emotional: { label: "Emotional", color: "#ec4899" },
  reaction: { label: "Reaction", color: "#a855f7" },
  storytelling: { label: "Story", color: "#06b6d4" },
  awkward: { label: "Awkward", color: "#f59e0b" },
  hype: { label: "Hype", color: "#d946ef" },
};

function formatDuration(seconds: number): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  return h > 0 ? `${h}h${m.toString().padStart(2, "0")}` : `${m}min`;
}

function formatTime(seconds: number): string {
  const m = Math.floor(seconds / 60);
  const s = Math.floor(seconds % 60);
  return `${m}:${s.toString().padStart(2, "0")}`;
}

function ScoreBadge({ score }: { score: number }) {
  const pct = Math.round(score * 100);
  const color =
    score > 0.7 ? "from-red-500 to-orange-500" :
    score > 0.5 ? "from-orange-500 to-yellow-500" :
    "from-zinc-500 to-zinc-400";
  return (
    <span className={`text-xs font-bold px-2.5 py-1 rounded-lg bg-gradient-to-r ${color} text-white`}>
      {pct}%
    </span>
  );
}

function CategoryBadge({ category }: { category: string }) {
  const style = CATEGORY_STYLES[category] || { label: category, color: "#71717a" };
  return (
    <span
      className="text-xs font-semibold px-2.5 py-1 rounded-lg"
      style={{ backgroundColor: `${style.color}20`, color: style.color }}
    >
      {style.label}
    </span>
  );
}

function SignalBars({ signals, activeSignals }: { signals: HotPoint["signals"]; activeSignals: SignalInfo[] }) {
  return (
    <div className="grid grid-cols-2 sm:grid-cols-3 gap-x-4 gap-y-1.5">
      {activeSignals.map((signal) => {
        const value = signals[signal.key];
        return (
          <div key={signal.key} className="flex items-center gap-2">
            <span className="text-[10px] text-zinc-500 w-14 text-right shrink-0">{signal.label}</span>
            <div className="flex-1 h-1 bg-white/[0.04] rounded-full overflow-hidden">
              <div
                className="h-full rounded-full transition-all"
                style={{
                  width: `${Math.round(value * 100)}%`,
                  backgroundColor: signal.color,
                  boxShadow: value > 0.5 ? `0 0 8px ${signal.color}60` : "none",
                }}
              />
            </div>
          </div>
        );
      })}
    </div>
  );
}

function ClipCard({
  point,
  index,
  jobId,
  activeSignals,
}: {
  point: HotPoint;
  index: number;
  jobId: string;
  activeSignals: SignalInfo[];
}) {
  const [expanded, setExpanded] = useState(false);
  const [showVertical, setShowVertical] = useState(false);
  const [activeMoment, setActiveMoment] = useState<number | null>(null);
  const videoRef = useRef<HTMLVideoElement>(null);

  const displayScore = point.final_score ?? point.score;
  const moments = point.llm?.key_moments ?? [];

  const seekTo = useCallback((time: number, momentIdx: number) => {
    if (videoRef.current) {
      videoRef.current.currentTime = time;
      videoRef.current.play();
    }
    setActiveMoment(momentIdx);
  }, []);

  return (
    <div className="glass rounded-2xl overflow-hidden ambient-glow transition-all">
      {/* Header row */}
      <button
        className="w-full p-5 text-left cursor-pointer"
        onClick={() => setExpanded(!expanded)}
      >
        <div className="flex items-start justify-between mb-3">
          <div className="flex items-center gap-3">
            <span className="text-xs font-bold text-zinc-600 bg-white/[0.04] w-7 h-7 rounded-full flex items-center justify-center shrink-0">
              {index + 1}
            </span>
            <div className="flex items-center flex-wrap gap-2">
              <span className="text-base font-mono text-white">{point.timestamp_display}</span>
              <ScoreBadge score={displayScore} />
              {point.llm?.category && <CategoryBadge category={point.llm.category} />}
              {point.chat_mood && (
                <span className="text-[10px] font-medium px-2 py-0.5 rounded-full bg-white/[0.04] text-zinc-400 capitalize">
                  {point.chat_mood}
                </span>
              )}
              {point.llm && point.llm.virality_score > 0 && (
                <span className="text-[10px] font-medium px-2 py-0.5 rounded-full bg-fuchsia-500/10 text-fuchsia-400">
                  Viral {Math.round(point.llm.virality_score * 100)}%
                </span>
              )}
            </div>
          </div>
          <svg
            className={`w-4 h-4 text-zinc-600 transition-transform shrink-0 mt-1 ${expanded ? "rotate-180" : ""}`}
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
          </svg>
        </div>

        {/* Summary */}
        {point.llm?.summary && (
          <p className="text-sm text-zinc-400 mb-3 line-clamp-2">{point.llm.summary}</p>
        )}

        {/* Signal bars */}
        <SignalBars signals={point.signals} activeSignals={activeSignals} />
      </button>

      {/* Expanded view */}
      {expanded && (
        <div className="border-t border-white/[0.04]">
          {/* Video */}
          {point.clip_filename && (
            <div className="p-4">
              {/* Format toggle */}
              {point.vertical_filename && (
                <div className="flex gap-2 mb-3">
                  {[
                    { label: "Clip brut (16:9)", vertical: false },
                    { label: "Vertical (9:16)", vertical: true },
                  ].map(({ label, vertical }) => (
                    <button
                      key={label}
                      className={`text-xs px-3 py-1.5 rounded-lg transition-all ${
                        showVertical === vertical
                          ? "bg-purple-500/20 text-purple-300 border border-purple-500/30"
                          : "glass text-zinc-500 hover:text-white"
                      }`}
                      onClick={() => setShowVertical(vertical)}
                    >
                      {label}
                    </button>
                  ))}
                </div>
              )}

              {showVertical && point.vertical_filename ? (
                <div className="flex justify-center">
                  <video
                    controls
                    className="max-h-[500px] rounded-xl"
                    src={clipUrl(jobId, point.vertical_filename)}
                  />
                </div>
              ) : (
                <>
                  <video
                    ref={videoRef}
                    controls
                    className="w-full max-h-[400px] rounded-xl"
                    src={clipUrl(jobId, point.clip_filename)}
                  />

                  {/* Key moments timeline */}
                  {moments.length > 0 && (
                    <div className="mt-3 flex flex-wrap gap-2">
                      {moments.map((moment, mi) => (
                        <button
                          key={mi}
                          className={`text-xs px-3 py-1.5 rounded-lg transition-all ${
                            activeMoment === mi
                              ? "bg-purple-500/20 text-purple-300 border border-purple-500/30"
                              : "glass text-zinc-400 hover:text-white"
                          }`}
                          onClick={() => seekTo(moment.time, mi)}
                          title={moment.description}
                        >
                          <span className="font-mono text-zinc-600 mr-1">{formatTime(moment.time)}</span>
                          {moment.label}
                        </button>
                      ))}
                    </div>
                  )}
                </>
              )}
            </div>
          )}

          {/* LLM Analysis */}
          {point.llm && (
            <div className="p-5 border-t border-white/[0.04] space-y-4">
              {/* Narrative */}
              {point.llm.narrative && (
                <div>
                  <h4 className="text-[10px] font-semibold text-zinc-600 uppercase tracking-widest mb-2">
                    Recit du clip
                  </h4>
                  <p className="text-sm text-zinc-300 leading-relaxed">{point.llm.narrative}</p>
                </div>
              )}

              {/* Tags */}
              <div className="flex flex-wrap gap-2 text-xs">
                {point.llm.category && <CategoryBadge category={point.llm.category} />}
                {point.llm.virality_score > 0 && (
                  <span className="px-2.5 py-1 rounded-lg bg-fuchsia-500/10 text-fuchsia-400">
                    Potentiel viral : {Math.round(point.llm.virality_score * 100)}%
                  </span>
                )}
                {!point.llm.is_clipable && (
                  <span className="px-2.5 py-1 rounded-lg bg-white/[0.04] text-zinc-500">
                    Necessite du contexte
                  </span>
                )}
                {point.llm.speech_rate > 0 && (
                  <span className="px-2.5 py-1 rounded-lg bg-white/[0.04] text-zinc-500">
                    {point.llm.speech_rate.toFixed(1)} mots/s
                  </span>
                )}
              </div>

              {/* Key moments detail */}
              {moments.length > 0 && (
                <details className="text-xs group">
                  <summary className="text-zinc-600 cursor-pointer hover:text-zinc-300 transition-colors">
                    Moments cles ({moments.length})
                  </summary>
                  <div className="mt-2 space-y-1">
                    {moments.map((moment, mi) => (
                      <button
                        key={mi}
                        className="w-full text-left flex gap-3 p-2.5 rounded-xl hover:bg-white/[0.03] transition-colors"
                        onClick={() => seekTo(moment.time, mi)}
                      >
                        <span className="font-mono text-purple-400 shrink-0">
                          {formatTime(moment.time)}
                        </span>
                        <div>
                          <span className="text-zinc-200 font-medium">{moment.label}</span>
                          {moment.description && (
                            <p className="text-zinc-600 mt-0.5">{moment.description}</p>
                          )}
                        </div>
                      </button>
                    ))}
                  </div>
                </details>
              )}

              {/* Transcript */}
              {point.llm.transcript && (
                <details className="text-xs group">
                  <summary className="text-zinc-600 cursor-pointer hover:text-zinc-300 transition-colors">
                    Transcription
                  </summary>
                  <p className="mt-2 text-zinc-500 italic leading-relaxed">{point.llm.transcript}</p>
                </details>
              )}
            </div>
          )}

          {/* Score detail */}
          <div className="p-5 border-t border-white/[0.04] space-y-3">
            <div className="flex items-center gap-3">
              <span className="text-xs text-zinc-600">Score final</span>
              <span className="text-sm font-bold text-white">{Math.round(displayScore * 100)}%</span>
            </div>

            {point.final_score != null && (
              <div className="flex gap-4 text-[10px] text-zinc-600">
                <span>Heuristique : {Math.round(point.score * 100)}% (x0.3)</span>
                <span>
                  LLM : {point.llm ? Math.round(point.llm.virality_score * 100) : 0}% (x0.7)
                </span>
              </div>
            )}

            {/* Detailed signals */}
            <details className="text-xs">
              <summary className="text-zinc-600 cursor-pointer hover:text-zinc-300 transition-colors">
                Detail des signaux
              </summary>
              <div className="space-y-3 mt-3">
                {activeSignals.map((signal) => {
                  const value = point.signals[signal.key];
                  return (
                    <div key={signal.key}>
                      <div className="flex items-center justify-between mb-1">
                        <span className="text-xs font-medium" style={{ color: signal.color }}>
                          {signal.label}
                        </span>
                        <span className="text-xs font-mono text-zinc-400">
                          {Math.round(value * 100)}%
                        </span>
                      </div>
                      <div className="w-full h-1.5 bg-white/[0.04] rounded-full overflow-hidden">
                        <div
                          className="h-full rounded-full"
                          style={{
                            width: `${Math.round(value * 100)}%`,
                            backgroundColor: signal.color,
                            boxShadow: value > 0.5 ? `0 0 12px ${signal.color}40` : "none",
                          }}
                        />
                      </div>
                    </div>
                  );
                })}
              </div>
            </details>
          </div>
        </div>
      )}
    </div>
  );
}

export default function HotPoints({
  hotPoints,
  vodTitle,
  vodGame,
  vodDuration,
  jobId,
  streamer,
  viewCount,
  streamDate,
}: Props) {
  const activeSignals = SIGNALS.filter((signal) =>
    hotPoints.some((hp) => hp.signals[signal.key] > 0.01),
  );

  return (
    <div className="w-full max-w-4xl mx-auto">
      {/* VOD Header */}
      <div className="mb-10 text-center">
        <h2 className="text-2xl font-bold text-white mb-3">{vodTitle}</h2>
        <div className="flex flex-wrap items-center justify-center gap-3 text-sm">
          {streamer && (
            <span className="text-purple-400 font-semibold">{streamer}</span>
          )}
          {vodGame && <span className="text-zinc-400">{vodGame}</span>}
          {streamDate && <span className="text-zinc-600">{streamDate}</span>}
          <span className="text-zinc-600">{formatDuration(vodDuration)}</span>
          {viewCount > 0 && (
            <span className="text-zinc-600">{viewCount.toLocaleString()} vues</span>
          )}
        </div>
        <p className="text-zinc-600 text-sm mt-2">
          {hotPoints.length} moments forts detectes
        </p>
      </div>

      {/* Clips grid */}
      <div className="space-y-3">
        {hotPoints.map((point, i) => (
          <ClipCard
            key={i}
            point={point}
            index={i}
            jobId={jobId}
            activeSignals={activeSignals}
          />
        ))}
      </div>
    </div>
  );
}

// frontend/src/lib/components/HotPoints.svelte
<script lang="ts">
  import { clipUrl, type HotPoint, type KeyMoment } from "../api";

  let {
    hotPoints,
    vodTitle,
    vodGame,
    vodDuration,
    jobId,
    streamer = "",
    viewCount = 0,
    streamDate = "",
  }: {
    hotPoints: HotPoint[];
    vodTitle: string;
    vodGame: string;
    vodDuration: number;
    jobId: string;
    streamer?: string;
    viewCount?: number;
    streamDate?: string;
  } = $props();

  interface SignalInfo {
    label: string;
    color: string;
    bgColor: string;
    key: keyof HotPoint["signals"];
    description: string;
  }

  const SIGNALS: SignalInfo[] = [
    {
      label: "Volume",
      color: "bg-red-500",
      bgColor: "text-red-400",
      key: "rms",
      description: "Energie sonore (RMS). Un pic indique des cris, de l'excitation ou un moment fort sonore.",
    },
    {
      label: "Chat",
      color: "bg-purple-500",
      bgColor: "text-purple-400",
      key: "chat_speed",
      description: "Vitesse du chat Twitch (messages/seconde). Le chat qui s'emballe est un des meilleurs indicateurs de moment fort.",
    },
    {
      label: "Flux spectral",
      color: "bg-orange-500",
      bgColor: "text-orange-400",
      key: "spectral_flux",
      description: "Taux de changement dans le spectre audio. Detecte les transitions soudaines : explosion apres un silence, changement d'ambiance.",
    },
    {
      label: "Pitch",
      color: "bg-blue-500",
      bgColor: "text-blue-400",
      key: "pitch_variance",
      description: "Variance de la hauteur de voix. Une voix qui monte dans les aigus signale du stress, de la surprise ou de l'excitation.",
    },
    {
      label: "Brillance",
      color: "bg-green-500",
      bgColor: "text-green-400",
      key: "spectral_centroid",
      description: "Centre de gravite spectral. Un son brillant (hautes frequences) correspond souvent a une voix excitee ou energique.",
    },
    {
      label: "ZCR",
      color: "bg-zinc-400",
      bgColor: "text-zinc-400",
      key: "zcr",
      description: "Taux de passage par zero. Distingue bruit/cris de la parole normale. Un ZCR eleve peut indiquer des cris ou du bruit intense.",
    },
  ];

  let expandedClip = $state<number | null>(null);
  let videoElements: Record<number, HTMLVideoElement> = {};
  let activeMoment = $state<Record<number, number | null>>({});
  let showVertical = $state<Record<number, boolean>>({});

  function formatDuration(seconds: number): string {
    const h = Math.floor(seconds / 3600);
    const m = Math.floor((seconds % 3600) / 60);
    return h > 0 ? `${h}h${m.toString().padStart(2, "0")}` : `${m}min`;
  }

  function formatTime(seconds: number): string {
    const m = Math.floor(seconds / 60);
    const s = Math.floor(seconds % 60);
    return `${m}:${s.toString().padStart(2, "0")}`;
  }

  function toggleClip(index: number) {
    expandedClip = expandedClip === index ? null : index;
  }

  function seekTo(clipIndex: number, time: number, momentIndex: number) {
    const video = videoElements[clipIndex];
    if (video) {
      video.currentTime = time;
      video.play();
    }
    activeMoment[clipIndex] = momentIndex;
  }

  function scoreLabel(score: number): { text: string; class: string } {
    if (score > 0.7) return { text: "Tres fort", class: "text-red-400" };
    if (score > 0.5) return { text: "Fort", class: "text-orange-400" };
    if (score > 0.3) return { text: "Moyen", class: "text-yellow-400" };
    return { text: "Faible", class: "text-zinc-400" };
  }

  const CATEGORY_STYLES: Record<string, { label: string; bg: string; text: string }> = {
    fun: { label: "Fun", bg: "bg-yellow-500/20", text: "text-yellow-400" },
    rage: { label: "Rage", bg: "bg-red-500/20", text: "text-red-400" },
    clutch: { label: "Clutch", bg: "bg-emerald-500/20", text: "text-emerald-400" },
    skill: { label: "Skill", bg: "bg-blue-500/20", text: "text-blue-400" },
    fail: { label: "Fail", bg: "bg-orange-500/20", text: "text-orange-400" },
    emotional: { label: "Emotional", bg: "bg-pink-500/20", text: "text-pink-400" },
    reaction: { label: "Reaction", bg: "bg-purple-500/20", text: "text-purple-400" },
    storytelling: { label: "Story", bg: "bg-cyan-500/20", text: "text-cyan-400" },
    awkward: { label: "Awkward", bg: "bg-amber-500/20", text: "text-amber-400" },
    hype: { label: "Hype", bg: "bg-fuchsia-500/20", text: "text-fuchsia-400" },
  };

  function categoryStyle(cat: string) {
    return CATEGORY_STYLES[cat] || { label: cat, bg: "bg-zinc-500/20", text: "text-zinc-400" };
  }

  // Only show signals that have non-zero values across all hot points
  let activeSignals = $derived(
    SIGNALS.filter((signal) =>
      hotPoints.some((hp) => hp.signals[signal.key] > 0.01)
    )
  );
</script>

<div class="w-full max-w-4xl mx-auto">
  <!-- Header -->
  <div class="mb-8 text-center">
    <h2 class="text-2xl font-bold text-white mb-2">{vodTitle}</h2>
    <div class="flex flex-wrap items-center justify-center gap-3 text-sm text-zinc-400 mb-1">
      {#if streamer}
        <span class="text-purple-400 font-medium">{streamer}</span>
      {/if}
      {#if vodGame}
        <span>{vodGame}</span>
      {/if}
      {#if streamDate}
        <span class="text-zinc-500">{streamDate}</span>
      {/if}
      <span>{formatDuration(vodDuration)}</span>
      {#if viewCount}
        <span class="text-zinc-500">{viewCount} vues</span>
      {/if}
    </div>
    <p class="text-zinc-500 text-sm">
      {hotPoints.length} moments forts detectes
    </p>
  </div>

  <!-- Hot points list -->
  <div class="space-y-4">
    {#each hotPoints as point, i}
      {@const displayScore = point.final_score ?? point.score}
      {@const label = scoreLabel(displayScore)}
      {@const moments = point.llm?.key_moments ?? []}
      <div
        class="bg-zinc-800/50 border border-zinc-700/50 rounded-xl overflow-hidden hover:border-purple-500/30 transition-colors"
      >
        <!-- Header row (clickable) -->
        <button
          class="w-full p-5 text-left cursor-pointer"
          onclick={() => toggleClip(i)}
        >
          <div class="flex items-start justify-between mb-3">
            <div class="flex items-center gap-3">
              <span
                class="text-sm font-bold text-zinc-500 bg-zinc-800 w-8 h-8 rounded-full flex items-center justify-center shrink-0"
              >
                {i + 1}
              </span>
              <div>
                <span class="text-lg font-mono text-white">{point.timestamp_display}</span>
                <span
                  class="ml-3 text-sm font-semibold px-2 py-0.5 rounded-full {displayScore > 0.7
                    ? 'bg-red-500/20 text-red-400'
                    : displayScore > 0.5
                      ? 'bg-orange-500/20 text-orange-400'
                      : 'bg-zinc-700/50 text-zinc-400'}"
                >
                  {Math.round(displayScore * 100)}%
                </span>
                {#if point.llm?.category}
                  {@const cat = categoryStyle(point.llm.category)}
                  <span class="ml-2 text-xs font-semibold px-2 py-0.5 rounded-full {cat.bg} {cat.text}">
                    {cat.label}
                  </span>
                {/if}
                {#if point.llm && point.llm.virality_score > 0}
                  <span class="ml-2 text-xs font-medium px-2 py-0.5 rounded-full bg-fuchsia-500/15 text-fuchsia-400">
                    Viral {Math.round(point.llm.virality_score * 100)}%
                  </span>
                {/if}
              </div>
            </div>
            <span class="text-zinc-500 text-sm">
              {expandedClip === i ? "▲ Masquer" : "▼ Details"}
            </span>
          </div>

          <!-- Summary line -->
          {#if point.llm?.summary}
            <p class="text-sm text-zinc-400 mb-3 line-clamp-2">{point.llm.summary}</p>
          {/if}

          <!-- Compact signal bars -->
          <div class="grid grid-cols-2 sm:grid-cols-3 gap-2">
            {#each activeSignals as signal}
              <div class="flex items-center gap-2">
                <span class="text-xs text-zinc-500 w-16 text-right">{signal.label}</span>
                <div class="flex-1 bg-zinc-700/30 rounded-full h-1.5 overflow-hidden">
                  <div
                    class="{signal.color} h-full rounded-full transition-all"
                    style="width: {Math.round(point.signals[signal.key] * 100)}%"
                  ></div>
                </div>
              </div>
            {/each}
          </div>
        </button>

        <!-- Expanded detail view -->
        {#if expandedClip === i}
          <div class="border-t border-zinc-700/50">
            <!-- Video player with toggle raw/vertical -->
            {#if point.clip_filename}
              <div class="p-4 bg-black/30">
                <!-- Toggle buttons -->
                {#if point.vertical_filename}
                  <div class="flex gap-2 mb-3">
                    <button
                      class="text-xs px-3 py-1.5 rounded-lg transition-colors cursor-pointer {!showVertical[i] ? 'bg-purple-500/30 text-purple-300 border border-purple-500/50' : 'bg-zinc-700/40 text-zinc-400 border border-zinc-600/30 hover:text-white'}"
                      onclick={() => showVertical[i] = false}
                    >
                      Clip brut (16:9)
                    </button>
                    <button
                      class="text-xs px-3 py-1.5 rounded-lg transition-colors cursor-pointer {showVertical[i] ? 'bg-purple-500/30 text-purple-300 border border-purple-500/50' : 'bg-zinc-700/40 text-zinc-400 border border-zinc-600/30 hover:text-white'}"
                      onclick={() => showVertical[i] = true}
                    >
                      Vertical (9:16)
                    </button>
                  </div>
                {/if}

                {#if showVertical[i] && point.vertical_filename}
                  <div class="flex justify-center">
                    <video
                      controls
                      class="rounded-lg max-h-[500px]"
                      src={clipUrl(jobId, point.vertical_filename)}
                    >
                      <track kind="captions" />
                    </video>
                  </div>
                {:else}
                  <video
                    bind:this={videoElements[i]}
                    controls
                    class="w-full rounded-lg max-h-[400px]"
                    src={clipUrl(jobId, point.clip_filename)}
                  >
                    <track kind="captions" />
                  </video>

                  <!-- Key moments timeline (goto buttons) -->
                  {#if moments.length > 0}
                    <div class="mt-3 flex flex-wrap gap-2">
                      {#each moments as moment, mi}
                        <button
                          class="text-xs px-3 py-1.5 rounded-lg transition-colors cursor-pointer
                            {activeMoment[i] === mi
                              ? 'bg-purple-500/30 text-purple-300 border border-purple-500/50'
                              : 'bg-zinc-700/40 text-zinc-300 border border-zinc-600/30 hover:bg-zinc-700/60 hover:text-white'}"
                          onclick={() => seekTo(i, moment.time, mi)}
                          title={moment.description}
                        >
                          <span class="font-mono text-zinc-500 mr-1">{formatTime(moment.time)}</span>
                          {moment.label}
                        </button>
                      {/each}
                    </div>
                  {/if}
                {/if}
              </div>
            {/if}

            <!-- Narrative + LLM Analysis -->
            {#if point.llm}
              <div class="p-5 border-b border-zinc-700/50 space-y-3">
                <!-- Narrative (the "film" of the clip) -->
                {#if point.llm.narrative}
                  <div>
                    <h4 class="text-xs font-semibold text-zinc-500 uppercase tracking-wide mb-2">Recit du clip</h4>
                    <p class="text-sm text-zinc-200 leading-relaxed">{point.llm.narrative}</p>
                  </div>
                {/if}

                <!-- Tags -->
                <div class="flex flex-wrap gap-2 text-xs">
                  {#if point.llm.category}
                    {@const cat = categoryStyle(point.llm.category)}
                    <span class="px-2 py-1 rounded-full {cat.bg} {cat.text} font-semibold">{cat.label}</span>
                  {/if}
                  {#if point.llm.virality_score > 0}
                    <span class="px-2 py-1 rounded-full bg-fuchsia-500/15 text-fuchsia-400">
                      Potentiel viral : {Math.round(point.llm.virality_score * 100)}%
                    </span>
                  {/if}
                  {#if !point.llm.is_clipable}
                    <span class="px-2 py-1 rounded-full bg-zinc-700/50 text-zinc-400">
                      Necessite du contexte
                    </span>
                  {/if}
                  {#if point.llm.speech_rate > 0}
                    <span class="px-2 py-1 rounded-full bg-zinc-700/50 text-zinc-400">
                      {point.llm.speech_rate.toFixed(1)} mots/s
                    </span>
                  {/if}
                </div>

                <!-- Key moments detail list -->
                {#if moments.length > 0}
                  <details class="text-xs">
                    <summary class="text-zinc-500 cursor-pointer hover:text-zinc-300">
                      Moments cles ({moments.length})
                    </summary>
                    <div class="mt-2 space-y-2">
                      {#each moments as moment, mi}
                        <button
                          class="w-full text-left flex gap-3 p-2 rounded-lg hover:bg-zinc-700/30 transition-colors cursor-pointer"
                          onclick={() => seekTo(i, moment.time, mi)}
                        >
                          <span class="font-mono text-purple-400 shrink-0">{formatTime(moment.time)}</span>
                          <div>
                            <span class="text-zinc-200 font-medium">{moment.label}</span>
                            {#if moment.description}
                              <p class="text-zinc-500 mt-0.5">{moment.description}</p>
                            {/if}
                          </div>
                        </button>
                      {/each}
                    </div>
                  </details>
                {/if}

                <!-- Transcript -->
                {#if point.llm.transcript}
                  <details class="text-xs">
                    <summary class="text-zinc-500 cursor-pointer hover:text-zinc-300">Transcription</summary>
                    <p class="mt-2 text-zinc-400 italic leading-relaxed">{point.llm.transcript}</p>
                  </details>
                {/if}
              </div>
            {/if}

            <!-- Score detail -->
            <div class="p-5 space-y-4">
              <div class="flex items-center gap-2 mb-4">
                <span class="text-sm text-zinc-500">Score final :</span>
                <span class="text-lg font-bold {label.class}">
                  {Math.round(displayScore * 100)}% — {label.text}
                </span>
              </div>

              {#if point.final_score != null}
                <div class="flex gap-4 text-xs text-zinc-500 mb-2">
                  <span>Heuristique : {Math.round(point.score * 100)}% (x0.3)</span>
                  <span>LLM : {point.llm ? Math.round(point.llm.virality_score * 100) : 0}% (x0.7)</span>
                </div>
              {/if}

              <p class="text-xs text-zinc-600 mb-4">
                Le score combine l'analyse audio/chat (30%) et l'evaluation LLM du potentiel viral (70%).
              </p>

              <!-- Detailed signal breakdown -->
              <details class="text-sm">
                <summary class="text-zinc-500 cursor-pointer hover:text-zinc-300 text-xs">
                  Detail des signaux audio
                </summary>
                <div class="space-y-3 mt-3">
                  {#each activeSignals as signal}
                    {@const value = point.signals[signal.key]}
                    <div>
                      <div class="flex items-center justify-between mb-1">
                        <span class="text-sm font-medium {signal.bgColor}">{signal.label}</span>
                        <span class="text-sm font-mono text-zinc-300">{Math.round(value * 100)}%</span>
                      </div>
                      <div class="w-full bg-zinc-700/30 rounded-full h-2 overflow-hidden mb-1">
                        <div
                          class="{signal.color} h-full rounded-full"
                          style="width: {Math.round(value * 100)}%"
                        ></div>
                      </div>
                      <p class="text-xs text-zinc-600">{signal.description}</p>
                    </div>
                  {/each}
                </div>
              </details>
            </div>
          </div>
        {/if}
      </div>
    {/each}
  </div>
</div>
